site_name: LBM Wiki
nav:
  - Home:
    - Home: index.md
  - Documentation:
    - Main: documentation.md
    - Events: documentation/Events.md
    - JMP Tables: documentation/JMP_list.md
    - Locations & Doors: documentation/Location_doors.md
    - Parameter files: documentation/Param_file.md
  - Tutorials:
    - Main: tutorials.md
    - Set-up: tutorials/Setup.md
    - General tutorials: tutorials/General.md
    - Specific tutorials: tutorials/Specific.md 
  - Game Knowledge: gameknowledge.md
  - Tools: tools.md
theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    #- navigation.footer 
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link 
  language: en
  custom_dir: docs/overrides  
  palette:

    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple

    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

#repo_name: Luigi's Bigger Mansion/Wiki
#repo_url: https://github.com/Luigi-s-Bigger-Mansion/Wiki

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - abbr
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
