site_name: LBM Wiki
nav:
  - Home:
    - Home: index.md
  - Documentation:
    - Main page: documentation.md
    - Events: documentation/Events.md
    - JMP Tables: documentation/JMP.md
    - Flags: documentation/Flags.md
    - Locations & Doors: documentation/Maps_Rooms_Doors.md
    - Parameter files: documentation/Parameters.md  
  - Tutorials:
    - Tutorials: tutorials.md
  - Research:
    - Main page: research.md
    - File formats: research/file_formats.md
  - Tools: 
    - Main page: tools.md
    - General software: tools/general_software.md
    - file conversion tools: tools/convert_tools.md
    - editing tools: tools/edit_tools.md
  - Code:
    - RAM: codes/RAM_codes.md
    - DOL: codes/DOL_codes.md
    - AR codes: codes/AR_codes.md

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    #- navigation.footer 
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  custom_dir: docs/overrides    
  language: en
  palette:

    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple

    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

#repo_name: Luigi's Bigger Mansion/Wiki
#repo_url: https://github.com/Luigi-s-Bigger-Mansion/Wiki

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - abbr
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg