site_name: LBM Wiki
plugins:
  - search
  - git-revision-date-localized:
      exclude:
        - index.md
nav:
  - Home: index.md
  - Documentation:
    - Home: documentation.md
    - Events: documentation/Events.md
    - Flags: documentation/Flags.md
  - Tutorials:
    - tutorials.md
  - Research:
    - research.md
    - File formats: research/file_formats.md
  - Tools:
    - tools.md
    - General Software: tools/general_software.md
    - File Conversion Tools: tools/convert_tools.md
    - Editing Tools: tools/edit_tools.md
  - Code:
    - RAM: codes/RAM_codes.md
    - DOL: codes/DOL_codes.md
    - AR codes: codes/AR_codes.md

theme:
  name: material
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  custom_dir: docs/overrides
  language: en
  palette:

    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

#repo_name: Luigi's Bigger Mansion/Wiki
#repo_url: https://github.com/Luigi-s-Bigger-Mansion/Wiki

extra_css:
  - stylesheets/extra.css
  - stylesheets/neoteroi-mkdocs.css

markdown_extensions:
  - neoteroi.cards
  - neoteroi.spantable
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - def_list
  - abbr
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - glossary.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
